name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-and-lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Check Formatting with Black
        run: |
          black --check .

  build-and-push-docker:
    needs: format-and-lint
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          load: true # Set to true to load the image into Docker runtime, useful for testing
          cache-from: type=local,src=docker-cache
          cache-to: type=local,dest=docker-cache-new
      - name: Move Docker cache
        if: success()
        run: |
          rm -rf docker-cache
          mv docker-cache-new docker-cache
