name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      tags:
        - "v*.*.*"
    pull_request:
    branches:
      - main

jobs:
  format-and-lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Check Formatting with Black
        run: |
          black --check .

  build-docker:
    needs: format-and-lint
    name: Build Docker Image
    if: ${{ needs.meta.outputs.tags }} # This assumes you have a job or step that sets outputs.tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: hicsail/notification-service
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          if: ${{ steps.meta.outputs.tags }} 
          file: ./Dockerfile
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=docker-cache
          cache-to: type=local,dest=docker-cache-new
      - name: Move Docker cache
        if: success()
        run: |
          rm -rf docker-cache
          mv docker-cache-new docker-cache
