name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-and-lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Clone and install picozk
        run: |
          git clone https://github.com/uvm-plaid/picozk.git
          cd picozk
          pip install .
      - name: Check Formatting with Black
        run: |
          black --check .
      - name: Run madlibs
        run: python copyright_madlibs.py
      - name: Run phonebook
        run: python copyright_phonebook.py